# function to generate plots that compare sequencting data from empty wells to single cell wells

library(ggplot2)

# CHANGEME: point df to the csv that is generated by the MultiQC data cleaner

df = read.csv("")

# function to determine the retention rates broken out by cell count

cpc_retention_ntc <- function(df){
  
  a <- ggplot(df, aes(factor(cell_count), cpc_retention)) +
    geom_jitter(width = 0.25, aes(color = factor(cell_count)), show.legend = FALSE) +
    xlab("cells per library") + ylab("CpC retention (%)") + ylim(0,100) +
    theme_bw()
  
  a
}

cpc_retention_ntc(df)

# function to determine the percentage of optimally aligned reads broke out by cell count

optimally_aligned_ntc <- function(df){
  
  b <- ggplot(df, aes(factor(cell_count), percent_reads_optimally_aligned)) +
    geom_jitter(width = 0.25, aes(color = factor(cell_count)), show.legend = FALSE) +
    xlab("cells per library") + ylab("optimally aligned reads (%)") + ylim(0,100) +
    theme_bw()
  
  b
}

optimally_aligned_ntc(df)